#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : xss-lock
Version  : 0.3.0
Release  : 1
URL      : https://bitbucket.org/raymonad/xss-lock/get/v0.3.0.tar.gz
Source0  : https://bitbucket.org/raymonad/xss-lock/get/v0.3.0.tar.gz
Summary  : No detailed summary available
Group    : Development/Tools
License  : MIT
Requires: xss-lock-bin = %{version}-%{release}
Requires: xss-lock-data = %{version}-%{release}
BuildRequires : buildreq-cmake
BuildRequires : pkgconfig(gio-unix-2.0)
BuildRequires : pkgconfig(glib-2.0)
BuildRequires : pkgconfig(xcb)
BuildRequires : pkgconfig(xcb-event)
BuildRequires : pkgconfig(xcb-screensaver)

%description
No detailed description available

%package bin
Summary: bin components for the xss-lock package.
Group: Binaries
Requires: xss-lock-data = %{version}-%{release}

%description bin
bin components for the xss-lock package.


%package data
Summary: data components for the xss-lock package.
Group: Data

%description data
data components for the xss-lock package.


%package doc
Summary: doc components for the xss-lock package.
Group: Documentation

%description doc
doc components for the xss-lock package.


%prep
%setup -q -n raymonad-xss-lock-94aec045ffd6
cd %{_builddir}/raymonad-xss-lock-94aec045ffd6

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1580657652
mkdir -p clr-build
pushd clr-build
export GCC_IGNORE_WERROR=1
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
export CFLAGS="$CFLAGS -O3 -ffat-lto-objects -flto=4 "
export FCFLAGS="$CFLAGS -O3 -ffat-lto-objects -flto=4 "
export FFLAGS="$CFLAGS -O3 -ffat-lto-objects -flto=4 "
export CXXFLAGS="$CXXFLAGS -O3 -ffat-lto-objects -flto=4 "
%cmake ..
make  %{?_smp_mflags}  VERBOSE=1
popd

%install
export SOURCE_DATE_EPOCH=1580657652
rm -rf %{buildroot}
pushd clr-build
%make_install
popd

%files
%defattr(-,root,root,-)

%files bin
%defattr(-,root,root,-)
/usr/bin/xss-lock

%files data
%defattr(-,root,root,-)
/usr/share/bash-completion/completions/xss-lock
/usr/share/zsh/site-functions/_xss-lock

%files doc
%defattr(0644,root,root,0755)
%doc /usr/share/doc/xss\-lock/*
